.PHONY: all
all: generate-limits

generate-limits: generate-limits.o

generate-limits.o: generate-limits.c

.PHONY: clean
clean:
	$(RM) generate-limits.o generate-limits

.PHONY: test
test:

.PHONY: install
install:

